package org.octank.claims.oracle.model;
// Generated Nov 28, 2018 2:14:25 PM by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Claim generated by hbm2java
 */
@Entity
@Table(name = "CLAIM")
public class Claim implements java.io.Serializable {

	private String claimId;
	private MedicalProvider medicalProvider;
	private Patient patient;
	private InsuranceCompany insuranceCompany;
	private Staff staff;
	private String claimStatus;
	private Date updatedDate;
	private BigDecimal amountClaimed;
	private BigDecimal amountPaid;
	private String insurancePolicyNbr;
	private String medicalCode;

	public Claim() {
	}

	public Claim(String claimId) {
		this.claimId = claimId;
	}

	public Claim(String claimId, MedicalProvider medicalProvider, Patient patient, InsuranceCompany insuranceCompany,
			Staff staff, String claimStatus, Date updatedDate, BigDecimal amountClaimed, BigDecimal amountPaid,
			String insurancePolicyNbr, String medicalCode) {
		this.claimId = claimId;
		this.medicalProvider = medicalProvider;
		this.patient = patient;
		this.insuranceCompany = insuranceCompany;
		this.staff = staff;
		this.claimStatus = claimStatus;
		this.updatedDate = updatedDate;
		this.amountClaimed = amountClaimed;
		this.amountPaid = amountPaid;
		this.insurancePolicyNbr = insurancePolicyNbr;
		this.medicalCode = medicalCode;
	}

	@Id

	@Column(name = "CLAIM_ID", unique = true, nullable = false, length = 20)
	
	
	public String getClaimId() {
		return this.claimId;
	}

	public void setClaimId(String claimId) {
		this.claimId = claimId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDICAL_PROVIDER_ID")
	public MedicalProvider getMedicalProvider() {
		return this.medicalProvider;
	}

	public void setMedicalProvider(MedicalProvider medicalProvider) {
		this.medicalProvider = medicalProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PATIENT_ID")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSURANCE_COMPANY_ID")
	public InsuranceCompany getInsuranceCompany() {
		return this.insuranceCompany;
	}

	public void setInsuranceCompany(InsuranceCompany insuranceCompany) {
		this.insuranceCompany = insuranceCompany;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STAFF_ID")
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@Column(name = "CLAIM_STATUS", length = 20)
	public String getClaimStatus() {
		return this.claimStatus;
	}

	public void setClaimStatus(String claimStatus) {
		this.claimStatus = claimStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "AMOUNT_CLAIMED", precision = 10)
	public BigDecimal getAmountClaimed() {
		return this.amountClaimed;
	}

	public void setAmountClaimed(BigDecimal amountClaimed) {
		this.amountClaimed = amountClaimed;
	}

	@Column(name = "AMOUNT_PAID", precision = 10)
	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	@Column(name = "INSURANCE_POLICY_NBR", length = 20)
	public String getInsurancePolicyNbr() {
		return this.insurancePolicyNbr;
	}

	public void setInsurancePolicyNbr(String insurancePolicyNbr) {
		this.insurancePolicyNbr = insurancePolicyNbr;
	}
	
	@Column(name = "MEDICAL_CODE", length = 20)
	public String getMedicalCode() {
		return this.medicalCode;
	}

	public void setMedicalCode(String medicalCode) {
		this.medicalCode = medicalCode;
	}

}
