package org.octank.claims.oracle.model;
// Generated Nov 28, 2018 2:14:25 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "STAFF")
public class Staff implements java.io.Serializable {

	private String staffId;
	private String staffCategory;
	private String gender;
	private String staffName;
	private Date staffBirthDate;
	private Set<Claim> claims = new HashSet<Claim>(0);

	public Staff() {
	}

	public Staff(String staffId) {
		this.staffId = staffId;
	}

	public Staff(String staffId, String staffCategory, String gender, String staffName, Date staffBirthDate,
			Set<Claim> claims) {
		this.staffId = staffId;
		this.staffCategory = staffCategory;
		this.gender = gender;
		this.staffName = staffName;
		this.staffBirthDate = staffBirthDate;
		this.claims = claims;
	}

	@Id

	@Column(name = "STAFF_ID", unique = true, nullable = false, length = 20)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "STAFF_CATEGORY", length = 20)
	public String getStaffCategory() {
		return this.staffCategory;
	}

	public void setStaffCategory(String staffCategory) {
		this.staffCategory = staffCategory;
	}

	@Column(name = "GENDER", length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "STAFF_NAME", length = 20)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STAFF_BIRTH_DATE", length = 7)
	public Date getStaffBirthDate() {
		return this.staffBirthDate;
	}

	public void setStaffBirthDate(Date staffBirthDate) {
		this.staffBirthDate = staffBirthDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Claim> getClaims() {
		return this.claims;
	}

	public void setClaims(Set<Claim> claims) {
		this.claims = claims;
	}

}
